import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Link from "next/link";
import { PlusSquare } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex">
          <Sidebar />
          <div className="flex-1 min-h-screen p-4 md:p-8">{children}</div>
        </div>
        <div className="fab">
          <Link href="/compose">
            <button className="rounded-full px-4 py-3 btn-primary flex items-center gap-2">
              <PlusSquare size={18} /> Compose
            </button>
          </Link>
        </div>
      </body>
    </html>
  );
}
